[package]
name = "pac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rp2040-boot2 = "0.3"
cortex-m-rt = "0.7.3"
cortex-m = "=0.7.7"
rp2040-pac = "0.6.0"
